### PR TITLE
CMake changes to support Clang toolchain, Debian Packaging, Unit test cases, and Yocto

### PR DESCRIPTION
**Pull request by jwinarske**
This PR enables building with different toolchain files.  With these changes, I am able to build with Clang 11.  [Clang_11_warnings.zip](https://github.com/Yours3lf/rpi-vk-driver/files/4808693/Clang_11_warnings.zip)

* CPU tuning comes from the toolchain file, as it's specific to the toolchain in use.  
* -fPIC was moved to the top level, given it's common to all.

The stack is building in the vulkan branch of my [flutter_embedded](https://github.com/jwinarske/flutter_embedded) project.

I can add support for Debian packaging if you like.

### CODE REVIEW

**Comment by Yours3lf** [comment]
Hi, 

thanks for making the changes necessary to get clang working, I gave it a go and seems like the changed build locations break the install script. I also can't call this a Vulkan driver so please don't put that in the CMakeLists.txt file.
I'd also like to keep the C11 standard unless there's a specific reason not to and also the ability to compile specifically for ARMv6/7/8.

Can you please fix these so I can merge your changes? Thanks!

**Comment by madscientist42** [comment]
There's issues with this building for Yocto.  You've got several assumptions I'm working on here.

1. Specifying an -march like you do causes problems with cross-compile on systems like Yocto (And you should care about that...  Balena, PHA Linux (waves), and a handful of others use it...)
1. How does anyone know if they're complying with terms of licensing or not?  YOU claim MIT, but some of those libraries can change the licensing on you in a heartbeat.   You really, really shouldn't do, "external," libs this way.

**Comment by Yours3lf** [comment]
> There's issues with this building for Yocto. You've got several assumptions I'm working on here.
> 
> 1. Specifying an -march like you do causes problems with cross-compile on systems like Yocto (And you should care about that...  Balena, PHA Linux (waves), and a handful of others use it...)
> 2. How does anyone know if they're complying with terms of licensing or not?  YOU claim MIT, but some of those libraries can change the licensing on you in a heartbeat.   You really, really shouldn't do, "external," libs this way.

thanks for noticing this, can you please submit a pull request with modifications so I can review them?

**Comment by jwinarske** [comment]
I made tools get discovered, so they need to be in the path.

My build scheme.  zlib is missing in the tools sysroot, were you manually adding that?

I can add a custom "install_user" step that's not part of "all", and it would replace install.sh.  That work?

```
git clone https://github.com/Yours3lf/rpi-vk-driver.git
cd rpi-vk-driver
git clone https://github.com/raspberrypi/tools.git

# add tools to path
export PATH=/media/joel/SolidState/rpi-vk-driver/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin:$PATH

mkdir build && cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DCMAKE_BUILD_TYPE=Debug
make -j48
```

**Comment by jwinarske** [comment]
This change replaces install.sh

Test scheme.  Install toolchain as reference above, and add to path.  Of course add zlib.h and zconf.h to sysroot if using default.

CMAKE_INSTALL_PREFIX is used to install everything into directory in build dir.

```
cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=./out
make install
make install_user
```

**Comment by MuAlphaOmegaEpsilon** [comment]
Please don't create dotfiles or dotdirs inside the home directory, even if it is part of a custom command.
I still don't get the reasoning behind most of the changes. If this should enable the build with a toolchain file, then why are you changing defaults all over the place?

**Comment by jwinarske** [comment]
@Yours3lf I believe I covered all your requests.

* When you use the add_subdirectory the parent key/values carry into the child, hence the use of top level standard setting.  The driver uses set_target_properties to override standard to C11.  So it minimizes redundant key/value entries.

* The toolchain triple override allows using Aarch64 compiler, hence 64-bit builds.  The adjusted toolchain will auto-discover the toolchain path based on the toolchain triple.  This doesn't impact using Yocto toolchain.

* Moving the compiler-specific tuning (-march) into the toolchain allows Yocto toolchain file to properly set based on platform.  Clang uses different flags for tuning, hence the change.

* I would argue moving the autoloader and driver away from $HOME.  It would make install and packaging cleaner.

* In the case of Yocto the loader gets built from scratch, so RPATH is controlled.

* I added dependency statements to enable -j building.  Prior to this it would fail.  Yocto will by default use ninja -j.  A simple test for -j support is:
    ```
    cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DCMAKE_INSTALL_PREFIX=./out
    make install -j
    ```

My changes support Linux host GCC/Clang, Yocto GCC/Clang, and on target building with Ubuntu or Raspbian.

**Comment by paulwratt** [comment]
> My changes support Linux host GCC/Clang, Yocto GCC/Clang, and on target building with Ubuntu or Raspbian.

thanks @jwinarske thats good coverage, hope it enough to satisfy future usage

**Comment by jwinarske** [comment]
Baseline Yocto recipes working:
https://github.com/jwinarske/meta-flutter/tree/zeus/recipes-graphics/rpi-vk-driver
https://github.com/jwinarske/meta-flutter/tree/zeus/recipes-graphics/vulkan

I was able to build rpi-vk-driver on rpi0w, and rpi3-64 projects.  Should scale on all others.

**Comment by jwinarske** [comment]
not done yet.

**Comment by jwinarske** [comment]
@Yours3lf  Ready for broader testing.

I updated BUILD.md, which covers the general scenarios.  Let me know if you need more documentation.

**Comment by jwinarske** [comment]
```
pi@raspberrypi:~ $ ./vulkaninfo
==========
VULKANINFO
==========

Vulkan Instance Version: 1.2.141


Instance Extensions: count = 4
==============================
	VK_EXT_debug_report : extension revision 9
	VK_EXT_debug_utils  : extension revision 1
	VK_KHR_display      : extension revision 21
	VK_KHR_surface      : extension revision 25

Layers: count = 0
=================
Device Properties and Extensions:
=================================
GPU0:
VkPhysicalDeviceProperties:
---------------------------
	apiVersion     = 4198400 (1.1.0)
	driverVersion  = 1 (0x0001)
	vendorID       = 0x14e4
	deviceID       = 0x5250
	deviceType     = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName     = VideoCore IV HW

VkPhysicalDeviceLimits:
-----------------------
	maxImageDimension1D                             = 2048
	maxImageDimension2D                             = 2048
	maxImageDimension3D                             = 0
	maxImageDimensionCube                           = 2048
	maxImageArrayLayers                             = 2048
	maxTexelBufferElements                          = 134217728
	maxUniformBufferRange                           = 4294967295
	maxStorageBufferRange                           = 4294967295
	maxPushConstantsSize                            = 256
	maxMemoryAllocationCount                        = 4096
	maxSamplerAllocationCount                       = 4000
	bufferImageGranularity                          = 0x00000400
	sparseAddressSpaceSize                          = 0xffffffff
	maxBoundDescriptorSets                          = 8
	maxPerStageDescriptorSamplers                   = 4000
	maxPerStageDescriptorUniformBuffers             = 12
	maxPerStageDescriptorStorageBuffers             = 4096
	maxPerStageDescriptorSampledImages              = 16384
	maxPerStageDescriptorStorageImages              = 16384
	maxPerStageDescriptorInputAttachments           = 8
	maxPerStageResources                            = 53268
	maxDescriptorSetSamplers                        = 4000
	maxDescriptorSetUniformBuffers                  = 72
	maxDescriptorSetUniformBuffersDynamic           = 72
	maxDescriptorSetStorageBuffers                  = 4096
	maxDescriptorSetStorageBuffersDynamic           = 16
	maxDescriptorSetSampledImages                   = 98304
	maxDescriptorSetStorageImages                   = 98304
	maxDescriptorSetInputAttachments                = 8
	maxVertexInputAttributes                        = 8
	maxVertexInputBindings                          = 8
	maxVertexInputAttributeOffset                   = 2047
	maxVertexInputBindingStride                     = 2048
	maxVertexOutputComponents                       = 128
	maxTessellationGenerationLevel                  = 0
	maxTessellationPatchSize                        = 0
	maxTessellationControlPerVertexInputComponents  = 0
	maxTessellationControlPerVertexOutputComponents = 0
	maxTessellationControlPerPatchOutputComponents  = 0
	maxTessellationControlTotalOutputComponents     = 0
	maxTessellationEvaluationInputComponents        = 0
	maxTessellationEvaluationOutputComponents       = 0
	maxGeometryShaderInvocations                    = 0
	maxGeometryInputComponents                      = 0
	maxGeometryOutputComponents                     = 0
	maxGeometryOutputVertices                       = 0
	maxGeometryTotalOutputComponents                = 0
	maxFragmentInputComponents                      = 128
	maxFragmentOutputAttachments                    = 8
	maxFragmentDualSrcAttachments                   = 1
	maxFragmentCombinedOutputResources              = 16
	maxComputeSharedMemorySize                      = 0
	maxComputeWorkGroupCount: count = 3
		0
		0
		0
	maxComputeWorkGroupInvocations                  = 0
	maxComputeWorkGroupSize: count = 3
		0
		0
		0
	subPixelPrecisionBits                           = 8
	subTexelPrecisionBits                           = 8
	mipmapPrecisionBits                             = 8
	maxDrawIndexedIndexValue                        = 65535
	maxDrawIndirectCount                            = 0
	maxSamplerLodBias                               = 15
	maxSamplerAnisotropy                            = 1
	maxViewports                                    = 1
	maxViewportDimensions: count = 2
		4096
		4096
	viewportBoundsRange: count = 2
		-8192
		8192
	viewportSubPixelBits                            = 8
	minMemoryMapAlignment                           = 64
	minTexelBufferOffsetAlignment                   = 0x00000010
	minUniformBufferOffsetAlignment                 = 0x00000100
	minStorageBufferOffsetAlignment                 = 0x00000020
	minTexelOffset                                  = -8
	maxTexelOffset                                  = 7
	minTexelGatherOffset                            = 0
	maxTexelGatherOffset                            = 0
	minInterpolationOffset                          = -0.5
	maxInterpolationOffset                          = 0.4375
	subPixelInterpolationOffsetBits                 = 4
	maxFramebufferWidth                             = 4096
	maxFramebufferHeight                            = 4096
	maxFramebufferLayers                            = 2048
	framebufferColorSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	framebufferDepthSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	framebufferStencilSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	framebufferNoAttachmentsSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	maxColorAttachments                             = 8
	sampledImageColorSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	sampledImageIntegerSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	sampledImageDepthSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	sampledImageStencilSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	storageImageSampleCounts: count = 2
		SAMPLE_COUNT_1_BIT
		SAMPLE_COUNT_4_BIT
	maxSampleMaskWords                              = 1
	timestampComputeAndGraphics                     = true
	timestampPeriod                                 = 1
	maxClipDistances                                = 8
	maxCullDistances                                = 8
	maxCombinedClipAndCullDistances                 = 8
	discreteQueuePriorities                         = 1
	pointSizeRange: count = 2
		1
		64
	lineWidthRange: count = 2
		0.5
		10
	pointSizeGranularity                            = 0
	lineWidthGranularity                            = 0.125
	strictLines                                     = false
	standardSampleLocations                         = true
	optimalBufferCopyOffsetAlignment                = 0x00000001
	optimalBufferCopyRowPitchAlignment              = 0x00000001
	nonCoherentAtomSize                             = 0x00000040

VkPhysicalDeviceSparseProperties:
---------------------------------
	residencyStandard2DBlockShape            = true
	residencyStandard2DMultisampleBlockShape = true
	residencyStandard3DBlockShape            = true
	residencyAlignedMipSize                  = true
	residencyNonResidentStrict               = true

Device Extensions: count = 8
	VK_EXT_debug_marker      : extension revision 4
	VK_KHR_display_swapchain : extension revision 9
	VK_KHR_driver_properties : extension revision 1
	VK_KHR_maintenance1      : extension revision 2
	VK_KHR_maintenance2      : extension revision 1
	VK_KHR_maintenance3      : extension revision 1
	VK_KHR_performance_query : extension revision 1
	VK_KHR_swapchain         : extension revision 70

VkQueueFamilyProperties:
========================
	queueProperties[0]:
	-------------------
		minImageTransferGranularity = (1,1,1)
		queueCount                  = 1
		queueFlags                  = QUEUE_GRAPHICS | QUEUE_COMPUTE | QUEUE_TRANSFER | QUEUE_SPARSE_BINDING
		timestampValidBits          = 64
		present support             = false

VkPhysicalDeviceMemoryProperties:
=================================
memoryHeaps: count = 1
	memoryHeaps[0]:
		size   = 262144000 (0x0fa00000) (250.00 MiB)
		budget = 0 (0x00000000) (0.00 B)
		usage  = 0 (0x00000000) (0.00 B)
		flags: count = 1
			MEMORY_HEAP_DEVICE_LOCAL_BIT
memoryTypes: count = 1
	memoryTypes[0]:
		heapIndex     = 0
		propertyFlags = 0x0007: count = 3
			MEMORY_PROPERTY_DEVICE_LOCAL_BIT
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				(non-sparse)
			IMAGE_TILING_LINEAR:
				color images
				(non-sparse)

VkPhysicalDeviceFeatures:
=========================
	robustBufferAccess                      = false
	fullDrawIndexUint32                     = false
	imageCubeArray                          = true
	independentBlend                        = true
	geometryShader                          = false
	tessellationShader                      = false
	sampleRateShading                       = false
	dualSrcBlend                            = true
	logicOp                                 = false
	multiDrawIndirect                       = false
	drawIndirectFirstInstance               = false
	depthClamp                              = true
	depthBiasClamp                          = true
	fillModeNonSolid                        = true
	depthBounds                             = true
	wideLines                               = true
	largePoints                             = true
	alphaToOne                              = true
	multiViewport                           = false
	samplerAnisotropy                       = false
	textureCompressionETC2                  = true
	textureCompressionASTC_LDR              = false
	textureCompressionBC                    = false
	occlusionQueryPrecise                   = false
	pipelineStatisticsQuery                 = true
	vertexPipelineStoresAndAtomics          = false
	fragmentStoresAndAtomics                = false
	shaderTessellationAndGeometryPointSize  = false
	shaderImageGatherExtended               = false
	shaderStorageImageExtendedFormats       = false
	shaderStorageImageMultisample           = false
	shaderStorageImageReadWithoutFormat     = false
	shaderStorageImageWriteWithoutFormat    = false
	shaderUniformBufferArrayDynamicIndexing = true
	shaderSampledImageArrayDynamicIndexing  = true
	shaderStorageBufferArrayDynamicIndexing = true
	shaderStorageImageArrayDynamicIndexing  = true
	shaderClipDistance                      = true
	shaderCullDistance                      = true
	shaderFloat64                           = false
	shaderInt64                             = false
	shaderInt16                             = true
	shaderResourceResidency                 = false
	shaderResourceMinLod                    = false
	sparseBinding                           = false
	sparseResidencyBuffer                   = false
	sparseResidencyImage2D                  = false
	sparseResidencyImage3D                  = false
	sparseResidency2Samples                 = false
	sparseResidency4Samples                 = false
	sparseResidency8Samples                 = false
	sparseResidency16Samples                = false
	sparseResidencyAliased                  = false
	variableMultisampleRate                 = false
	inheritedQueries                        = true

```

**Comment by jwinarske** [comment]
@Yours3lf This is ready.  Let me know what it will take to get this over the finish line.

**Comment by Yours3lf** [comment]
> I made tools get discovered, so they need to be in the path.
> 
> My build scheme. zlib is missing in the tools sysroot, were you manually adding that?
> 
> I can add a custom "install_user" step that's not part of "all", and it would replace install.sh. That work?
> 
> ```
> git clone https://github.com/Yours3lf/rpi-vk-driver.git
> cd rpi-vk-driver
> git clone https://github.com/raspberrypi/tools.git
> 
> # add tools to path
> export PATH=/media/joel/SolidState/rpi-vk-driver/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin:$PATH
> 
> mkdir build && cd build
> cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DCMAKE_BUILD_TYPE=Debug
> make -j48
> ```

Yes I was adding zlib manually, and other stuff if it was missing. 

I suppose an install user step would work :)

**Comment by Yours3lf** [comment]
"I would argue moving the autoloader and driver away from $HOME. It would make install and packaging cleaner."
I guess I didn't want root to be necessary, but then you do need it for the Vulkan loader lib.

**Comment by Yours3lf** [comment]
thank you so much for sorting this out!

**Comment by madscientist42** [comment]
I will get to building this weekend.  Heh...  WORK had me hopping with
other things this week so I didn't get to it like I had planned...

**Comment by madscientist42** [comment]
As for including things in your sources...you probably ought to avoid doing
that unless you have a really specific need.  You'll end up with issues and
conflicts with someone trying to package it all up- you probably want to
document dependencies and let the builder handle that for themselves.  I
know you want to try to make it self-contained, but that makes it a smidge
hard to package up for a distribution or in my context an embedded target.

**Comment by Yours3lf** [comment]
Well in my opinion, it's really nice when "it just works", I value that a lot :)

**Comment by madscientist42** [comment]
It gets in the way of people packaging.

Therein lies the rub.  You're making something that is a generic solution
for any distribution.   It's not like a Feral Interactive or LGP game title
where that is an actual, "thing," there.

**Pull request merged**
